server:
  port: 7000
  
feign:
  hystrix:
    enabled: true

spring:
  application:
    name: atguigu-feigh-consumer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:5000/eureka/
