server:
  port: 9000
spring:
  application:
    name: zuul-gateway
zuul:
  routes:
    emplyee:
      serviceId: atguigu-feigh-consumer
      path: /zuul-emp/**

  ignored-services:
    - atguigu-feigh-consumer

feign:
  hystrix:
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:5000/eureka/